
-- 63) Retrieve the list of courses where the number of students enrolled is less than a specific
-- threshold.
-- 64) Retrieve the list of students who have not completed a specific course but have submitted
-- all the assignments for that course.
-- 65) Retrieve the list of courses where the average grade is higher than the overall average
-- grade of all courses.
-- 66) Retrieve the list of courses where the average grade is higher than a specific threshold
-- and the number of students enrolled is greater than a specific threshold.
-- 67) Retrieve the list of students who have enrolled in at least two courses and have not
-- submitted any assignments in the past month.
-- 68) Retrieve the list of courses where the percentage of students who have submitted all the
-- assignments is higher than a specific threshold.
-- 69) Retrieve the list of students who have enrolled in a course but have not submitted any
-- assignments.
-- 70) Retrieve the list of courses where the percentage of students who have submitted at least
-- one assignment is lower than a specific threshold.
-- 71) Retrieve the list of students who have submitted an assignment after the due date.
-- 72) Retrieve the list of courses where the average grade of female students is higher than that
-- of male students.
-- 73) Retrieve the list of courses that have at least one female student and no male students.
-- 74) Retrieve the list of students who have submitted at least one assignment in all the courses
-- they are enrolled in.
-- 75) Retrieve the list of students who have not enrolled in any courses.
-- 76) Retrieve the list of courses that have the highest number of enrolled students.
-- 77) Retrieve the list of assignments that have the lowest average grade.
-- 78) Retrieve the list of students who have submitted all the assignments in a particular
-- course.
-- 79) Retrieve the list of courses where the average grade of all students is above 80.
-- 80) Retrieve the list of students who have the highest grade in each course.
-- 81) Retrieve the list of students who have submitted all the assignments on time.
-- 82) Retrieve the list of students who have submitted late submissions for any assignment.
-- 83) Retrieve the list of courses that have the lowest average grade for a particular semester.
-- 84) Retrieve the list of students who have not submitted any assignment for a particular
-- course.
-- 85) Retrieve the list of courses where the highest grade is less than 90.
-- 86) Retrieve the list of students who have submitted all the assignments, but their average
-- grade is less than 70.
-- 87) Retrieve the list of courses that have at least one student with an average grade of 90 or
-- above.
-- 88) Retrieve the list of students who have not submitted any assignments for any of their
-- enrolled courses.
-- 89) Retrieve the list of courses that have at least one student who has not submitted any
-- assignments.
-- 90) Retrieve the list of students who have submitted all the assignments for a particular
-- course.
-- 91) Retrieve the list of assignments that have not been graded yet for a particular course.
-- 92) Retrieve the list of students who have not enrolled in any courses.
-- 93) Retrieve the list of students who have submitted an assignment after the due date.
-- 94) Retrieve the list of courses that have more than 50 enrolled students.
-- 95) Retrieve the list of students who have submitted an assignment for a particular course but
-- have not received a grade yet.